#!/usr/bin/env python3
import json
import math
import os
import threading
import time
import unittest

import yaml

from emotion_bot_ros.contract import ContractError, EMOTIONS, build_state, dumps_state, loads_state
from emotion_bot_ros.hardware_transport import (
    MAX_FRAME_BYTES,
    SequenceGate,
    TransportError,
    build_envelope,
    decode_envelope,
    encode_envelope,
)
from emotion_bot_ros.conversation import (
    AssistantStateTracker,
    ConversationCoordinator,
    ConversationError,
    DeterministicChatBackend,
    TurnGate,
    chat_client_timeout,
    validate_conversation_event,
)
from emotion_bot_ros.mapping import (
    EXPRESSION_ACTIONS,
    FluidExpressionController,
    PatternPlayer,
    TwistValue,
    load_patterns,
)
from emotion_bot_ros.safety import (
    JoyValue,
    Limits,
    SafetyController,
    clamp_twist,
    home_return_target,
)


class FakeTime:
    secs = 12
    nsecs = 345


class ContractTests(unittest.TestCase):
    def test_all_emotions_round_trip_and_bounds(self):
        for sequence, emotion in enumerate(EMOTIONS):
            state = build_state(FakeTime(), sequence, emotion, -1.0, 1.0, "deterministic", "test")
            self.assertEqual(loads_state(dumps_state(state)), state)
            self.assertEqual(state["turn_id"], "system")

    def test_malformed_and_out_of_bounds_rejected(self):
        with self.assertRaises(ContractError):
            loads_state("not json")
        state = build_state(FakeTime(), 0, "neutral", 0.0, 0.2, "deterministic", "test")
        state["valence"] = 1.1
        with self.assertRaises(ContractError):
            loads_state(json.dumps(state))

    def test_hardware_transport_round_trip_and_replay_rejection(self):
        state = build_state(FakeTime(), 4, "joy", 0.8, 0.9, "deterministic", "user")
        first = decode_envelope(encode_envelope(build_envelope("session-a", 1, state)))
        second = decode_envelope(encode_envelope(build_envelope("session-a", 2, state)))
        gate = SequenceGate()
        self.assertTrue(gate.accept(first))
        self.assertFalse(gate.accept(first))
        self.assertTrue(gate.accept(second))
        self.assertTrue(gate.accept(build_envelope("session-b", 1, state)))

    def test_hardware_transport_rejects_oversize_and_extra_fields(self):
        state = build_state(FakeTime(), 4, "joy", 0.8, 0.9, "deterministic", "user")
        envelope = build_envelope("session-a", 1, state)
        envelope["unexpected"] = True
        with self.assertRaises(TransportError):
            encode_envelope(envelope)
        with self.assertRaises(TransportError):
            decode_envelope(b"{" + b" " * MAX_FRAME_BYTES + b"}\n")


class MappingAndSafetyTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        config_path = os.path.join(os.path.dirname(__file__), "..", "config", "default.yaml")
        with open(config_path, "r", encoding="utf-8") as stream:
            cls.patterns = load_patterns(yaml.safe_load(stream)["mappings"])

    def test_all_nine_profiles_have_bounded_transition_and_sustained_idle(self):
        self.assertEqual(set(self.patterns), set(EMOTIONS))
        player = PatternPlayer(self.patterns)
        for emotion in EMOTIONS:
            player.start(emotion, 10.0)
            self.assertIsInstance(player.command(10.0), TwistValue)
            # An emotion never falls silently through to zero: after its
            # entrance gesture it loops its designed idle body language.
            self.assertGreaterEqual(player.segment(30.0)[1], len(self.patterns[emotion].transition))
            self.assertTrue(self.patterns[emotion].idle)

    def test_anger_and_surprise_request_one_bounded_dynamic_action(self):
        stomp = [segment.twist for segment in self.patterns["anger"].transition]
        # The stroke is generated by the simulator's dedicated symmetric
        # stance trajectory, never by an external wrench or mapper pitch.
        self.assertEqual(stomp[0], TwistValue())
        self.assertLess(min(value.z for value in stomp), 0.0)
        self.assertLessEqual(max(abs(value.roll) for value in stomp), 0.50)
        self.assertEqual(
            [segment.action for segment in self.patterns["anger"].transition if segment.action != "none"], ["stomp"]
        )
        self.assertEqual(
            [segment.action for segment in self.patterns["surprise"].transition if segment.action != "none"], ["hop"]
        )

    def test_fluid_filter_blend_dwell_hysteresis_rate_and_neutral_decay(self):
        controller = FluidExpressionController(
            self.patterns,
            min_dwell=0.30,
            hysteresis=0.12,
            max_linear_rate=0.10,
            max_yaw_rate=0.20,
        )
        controller.command(0.0)
        controller.update("joy", 0.7, 0.6, 0.0)
        first = controller.command(0.20)
        self.assertEqual(controller.selected_emotion, "joy")
        # Joy begins with a centered anticipatory crouch; the discrete hop and
        # enlarged posture envelope provide the visible motion without drift.
        self.assertEqual(first.x, 0.0)
        self.assertLess(first.z, 0.0)
        self.assertLessEqual(abs(first.z), 0.024001)
        prance = controller.command(1.12)
        self.assertEqual(prance.x, 0.0)
        self.assertGreater(prance.z, 0.0)
        self.assertGreater(prance.roll, 0.0)
        self.assertLess(controller.filtered_arousal, 0.6)

        # A second appraisal in the same conversation turn adjusts intensity
        # without restarting the loop or duplicating dynamic actions.
        original_start = controller.player.started_at
        controller.update("joy", 0.7, 0.75, 0.62)
        self.assertEqual(controller.player.started_at, original_start)
        self.assertEqual(controller.selected_emotion, "joy")

        # Explicit category changes cancel immediately, reset through neutral,
        # and only then begin the next choreography.
        controller.update("curiosity", 0.71, 0.61, 0.63)
        self.assertEqual(controller.selected_emotion, "joy")
        self.assertEqual(controller.transition_emotion, "curiosity")
        controller.update("anger", -0.6, 0.8, 0.64)
        self.assertEqual(controller.transition_emotion, "anger")
        for moment in (0.70, 0.80, 0.90, 1.00, 1.10, 1.20):
            controller.command(moment)
        self.assertEqual(controller.selected_emotion, "anger")

        previous = controller.command(1.25)
        stale = controller.command(1.35, stale=True)
        self.assertLessEqual(abs(stale.x - previous.x), 0.010001)
        for index in range(1, 30):
            stale = controller.command(1.15 + index * 0.10, stale=True)
        self.assertEqual(stale, TwistValue())
        self.assertTrue(controller.inactive)

    def test_profile_action_is_emitted_once_and_suppressed_when_stale(self):
        controller = FluidExpressionController(self.patterns)
        controller.update("surprise", 0.0, 1.0, 0.0)
        self.assertEqual(controller.selected_emotion, "surprise")
        controller.command(0.0)
        cancel = controller.consume_action(0.0)
        start = controller.consume_action(0.01)
        self.assertEqual(cancel["kind"], "cancel")
        self.assertEqual(start["kind"], "start")
        self.assertEqual(start["action"], "hop")
        self.assertEqual(start["emotion"], "surprise")
        self.assertIn("occurrence_id", start)
        self.assertIsNone(controller.consume_action(0.2))
        stale_cancel = controller.consume_action(0.3, stale=True)
        self.assertEqual(stale_cancel["kind"], "cancel")
        self.assertGreater(stale_cancel["generation"], start["generation"])
        self.assertIsNone(controller.consume_action(0.31, stale=True))

    def test_quintic_interpolation_has_stationary_keyframe_boundaries(self):
        player = PatternPlayer(self.patterns)
        player.start("curiosity", 0.0)
        boundary = self.patterns["curiosity"].transition[0].duration
        epsilon = 1e-3
        before = player.command(boundary - epsilon)
        at = player.command(boundary)
        after = player.command(boundary + epsilon)
        for field in ("z", "roll", "pitch"):
            left_velocity = (getattr(at, field) - getattr(before, field)) / epsilon
            right_velocity = (getattr(after, field) - getattr(at, field)) / epsilon
            self.assertLess(abs(left_velocity), 0.001)
            self.assertLess(abs(right_velocity), 0.001)

    def test_idle_loop_seam_is_continuous_and_stationary(self):
        player = PatternPlayer(self.patterns)
        epsilon = 1e-3
        for emotion, profile in self.patterns.items():
            player.start(emotion, 0.0)
            transition = sum(item.duration for item in profile.transition) * profile.duration / profile.speed
            idle = sum(item.duration for item in profile.idle) / profile.speed
            seam = transition + idle
            before = player.command(seam - epsilon)
            at = player.command(seam)
            after = player.command(seam + epsilon)
            for field in ("x", "y", "yaw", "z", "roll", "pitch"):
                self.assertLess(abs(getattr(at, field) - getattr(before, field)), 1e-5)
                self.assertLess(abs(getattr(after, field) - getattr(at, field)), 1e-5)

    def test_idle_can_be_softer_and_slower_without_weakening_entrance(self):
        normal = PatternPlayer(self.patterns)
        softened = PatternPlayer(
            self.patterns, idle_amplitude_scale=0.65, idle_time_scale=1.25
        )
        profile = self.patterns["curiosity"]
        transition = sum(item.duration for item in profile.transition)
        normal.start("curiosity", 0.0)
        softened.start("curiosity", 0.0)

        # Entrance choreography is unchanged.
        self.assertEqual(normal.command(transition * 0.5), softened.command(transition * 0.5))

        # At the first softened-loop endpoint, amplitude is 65% of the authored
        # keyframe and the loop takes 25% longer.
        first_idle_end = transition + profile.idle[0].duration * 1.25
        soft_pose = softened.command(first_idle_end)
        expected = profile.idle[0].twist
        self.assertAlmostEqual(soft_pose.z, expected.z * 0.65)
        self.assertAlmostEqual(soft_pose.roll, expected.roll * 0.65)
        normal_idle = sum(item.duration for item in profile.idle)
        soft_idle = normal_idle * 1.25
        self.assertGreater(soft_idle, normal_idle)

    def test_active_neutral_breathes_but_stale_state_reaches_exact_zero(self):
        player = PatternPlayer(self.patterns)
        player.start("neutral", 0.0)
        self.assertGreater(player.command(0.50).z, 0.0)
        self.assertLess(player.command(1.25).z, 0.0)

        controller = FluidExpressionController(self.patterns)
        controller.update("neutral", 0.0, 0.2, 0.0)
        for moment in (0.1, 0.5, 1.0):
            active = controller.command(moment)
        self.assertGreater(active.z, 0.0)
        for index in range(1, 20):
            stale = controller.command(1.0 + index * 0.1, stale=True)
        self.assertEqual(stale, TwistValue())

    def test_crossfade_durations_match_choreography(self):
        for emotion, profile in self.patterns.items():
            expected = {
                "neutral": 0.14,
                "joy": 0.12,
                "sadness": 0.18,
                "anger": 0.12,
                "fear": 0.10,
                "surprise": 0.10,
                "disgust": 0.12,
                "curiosity": 0.12,
                "affection": 0.16,
            }[emotion]
            self.assertAlmostEqual(profile.transition_blend, expected)

    def test_joy_hops_and_both_phases_remain_centered(self):
        profile = self.patterns["joy"]
        transition = sum(item.duration for item in profile.transition)
        self.assertLessEqual(transition, 1.15)
        player = PatternPlayer(self.patterns)
        player.start("joy", 0.0)
        dt = 0.002
        self.assertTrue(any(segment.action == "hop" for segment in profile.transition))
        self.assertFalse(any(segment.twist.has_locomotion() for segment in profile.transition))
        for segment in profile.idle:
            self.assertFalse(segment.twist.has_locomotion())

    def test_anger_repeats_forceful_stomps_throughout_the_idle_loop(self):
        controller = FluidExpressionController(
            self.patterns, idle_amplitude_scale=0.65, idle_time_scale=1.25
        )
        controller.update("anger", -0.8, 1.0, 0.0)
        starts = []
        for index in range(401):
            now = index * 0.05
            controller.command(now)
            action = controller.consume_action(now)
            if action and action["kind"] == "start":
                starts.append(now)
        self.assertGreaterEqual(len(starts), 5)
        spacings = [second - first for first, second in zip(starts, starts[1:])]
        self.assertAlmostEqual(spacings[0], 1.50, delta=0.1)
        self.assertTrue(all(2.35 <= spacing <= 2.55 for spacing in spacings[1:4]))
        self.assertEqual(len(starts), len(set(starts)))

    def test_normal_keyframes_stay_inside_designed_envelope(self):
        for profile in self.patterns.values():
            for segment in profile.transition + profile.idle:
                self.assertLessEqual(abs(segment.twist.z), 0.080001)
                self.assertLessEqual(abs(segment.twist.roll), 0.500001)
                self.assertLessEqual(abs(segment.twist.pitch), 0.500001)

    def test_rapid_changes_blend_and_repeated_emotion_respects_cooldown(self):
        controller = FluidExpressionController(self.patterns, min_dwell=0.0)
        controller.update("joy", 0.7, 0.8, 0.0)
        first = controller.command(0.25)
        controller.update("fear", -0.6, 0.8, 0.26)
        changed = controller.command(0.27)
        self.assertEqual(controller.selected_emotion, "joy")
        self.assertEqual(controller.transition_emotion, "fear")
        # Neutral reset prevents an unsafe discontinuity on an interruption.
        self.assertLess(abs(changed.z - first.z), 0.10)
        controller.command(0.62)
        self.assertEqual(controller.selected_emotion, "fear")
        start = controller.player.started_at
        controller.update("fear", -0.6, 0.8, 0.63)
        self.assertEqual(controller.player.started_at, start)
        controller.update("fear", -0.6, 0.8, 1.20)
        self.assertEqual(controller.player.started_at, start)

    def test_emotion_change_cancels_then_reaches_neutral_before_new_action(self):
        controller = FluidExpressionController(
            self.patterns,
            neutral_return_time=0.35,
            neutral_hold_time=0.25,
            min_dwell=0.0,
        )
        controller.update("joy", 0.8, 0.9, 0.0)
        controller.command(0.0)
        controller.command(0.70)
        controller.consume_action(0.70)  # initial generation cancel
        self.assertFalse(controller.output.is_zero())

        controller.update("anger", -0.8, 1.0, 0.71)
        cancel = controller.consume_action(0.71)
        self.assertEqual(cancel["kind"], "cancel")
        self.assertIsNone(controller.consume_action(0.90))
        for moment in (0.81, 0.91, 1.01, 1.06):
            controller.command(moment)
        self.assertEqual(controller.output, TwistValue())
        self.assertEqual(controller.selected_emotion, "joy")
        self.assertEqual(controller.transition_emotion, "anger")

        # Exact neutral is held as a fresh canonical stance before the new
        # entrance begins; no prior pose residue can feed its first keyframe.
        self.assertEqual(controller.command(1.20), TwistValue())
        controller.command(1.32)
        self.assertEqual(controller.selected_emotion, "anger")
        self.assertEqual(controller.player.started_at, 1.32)

        # Starting the target is a separate generation after the reset, so a
        # stale action from joy cannot overtake anger's entrance stomp.
        target_cancel = controller.consume_action(1.32)
        stomp = controller.consume_action(1.33)
        self.assertEqual(target_cancel["kind"], "cancel")
        self.assertEqual(stomp["kind"], "start")
        self.assertEqual(stomp["emotion"], "anger")
        self.assertEqual(stomp["action"], "stomp")
        self.assertGreater(stomp["generation"], cancel["generation"])

    def test_clamps_every_expression_axis(self):
        result = clamp_twist(
            TwistValue(x=5.0, y=-6.0, yaw=float("nan"), z=2.0, roll=-2.0, pitch=2.0),
            Limits(),
        )
        self.assertEqual(
            result,
            TwistValue(x=0.10, y=-0.05, yaw=0.0, z=0.100, roll=-0.625, pitch=0.625),
        )

    def test_disabled_stale_disable_and_manual_priority(self):
        controller = SafetyController(Limits(), expression_timeout=0.5)
        controller.update_expression(TwistValue(z=0.5, roll=0.5, pitch=0.5), 0.0)
        disabled = controller.step(0.1)
        self.assertEqual(disabled.twist, TwistValue())

        controller.set_enabled(True, 0.1)
        controller.update_expression(TwistValue(z=0.5, roll=0.5, pitch=0.5), 0.1)
        controller.step(0.1)
        controller.step(0.5)
        bounded = controller.step(0.6)
        self.assertGreater(bounded.twist.z, 0.0)
        self.assertGreater(bounded.twist.roll, 0.0)
        self.assertLessEqual(bounded.twist.z, 0.100)
        self.assertLessEqual(bounded.twist.roll, 0.625)
        self.assertEqual(bounded.twist.x, 0.0)

        axes = [0.0] * 8
        axes[6] = -0.4
        controller.update_manual(axes, [0] * 11, 0.61)
        manual = controller.step(0.62)
        self.assertEqual(manual.selected_source, "manual")

        stale = controller.step(1.3)
        for moment in (1.4, 1.5, 1.6):
            stale = controller.step(moment)
        self.assertEqual(stale.twist, TwistValue())
        self.assertTrue(stale.stale)

        controller.set_enabled(False, 1.4)
        self.assertEqual(controller.step(1.4).twist, TwistValue())

    def test_seeded_decisions_repeat(self):
        def decisions():
            controller = SafetyController(Limits())
            controller.set_enabled(True, 0.0)
            controller.update_expression(TwistValue(z=0.01, roll=0.03), 0.0)
            return [controller.step(moment) for moment in (0.0, 0.4, 0.45)]
        self.assertEqual(decisions(), decisions())

    def test_manual_mode_button_is_a_single_pulse(self):
        controller = SafetyController(Limits(), allow_locomotion=True)
        controller.set_enabled(True, 0.0)
        buttons = [0] * 11
        buttons[2] = 1
        controller.update_manual([0.0] * 8, buttons, 0.0)
        first = controller.step(0.01)
        second = controller.step(0.02)
        self.assertEqual(first.joy.buttons[2], 1)
        self.assertEqual(second.joy.buttons[2], 0)

    def test_stance_can_be_prepared_while_motion_permission_is_disabled(self):
        controller = SafetyController(Limits())
        controller.request_stance_preparation(1.0)
        first = controller.step(1.0)
        second = controller.step(1.1)
        self.assertFalse(controller.motion_enabled)
        self.assertEqual(first.joy.buttons[1], 1)
        self.assertEqual(second.joy.buttons[1], 0)
        self.assertTrue(controller.stand_ready)

        controller.set_enabled(True, 1.1)
        controller.update_expression(TwistValue(z=0.01, roll=0.02), 1.1)
        expression = controller.step(1.2)
        self.assertEqual(expression.joy.buttons[1], 0)
        self.assertGreater(expression.twist.z, 0.0)
        self.assertGreater(expression.twist.roll, 0.0)

    def test_explicit_planted_mode_blocks_locomotion_but_allows_posture(self):
        controller = SafetyController(Limits(), allow_locomotion=False)
        controller.set_enabled(True, 0.0)
        controller.update_expression(TwistValue(x=0.05, z=0.01, roll=0.03), 0.0)
        self.assertEqual(controller.step(0.0).joy.buttons[1], 1)
        controller.step(0.4)
        decision = controller.step(0.5)
        self.assertEqual(decision.twist.x, 0.0)
        self.assertGreater(decision.twist.z, 0.0)
        self.assertGreater(decision.twist.roll, 0.0)
        self.assertEqual(decision.joy.axes[4], 0.0)

    def test_dynamic_actions_are_one_shot_and_never_enable_locomotion(self):
        controller = SafetyController(Limits())
        controller.request_stance_preparation(0.0)
        controller.step(0.0)
        controller.set_enabled(True, 0.1)
        controller.update_expression(TwistValue(z=0.02), 0.1)
        controller.update_expression_action("hop", 0.1)
        hop = controller.step(0.11)
        self.assertEqual(hop.joy.buttons[4], 1)
        self.assertEqual(hop.joy.buttons[5], 0)
        self.assertEqual(hop.joy.axes[4], 0.0)
        self.assertEqual(hop.joy.axes[3], 0.0)
        self.assertEqual(hop.joy.axes[0], 0.0)
        self.assertEqual(controller.step(0.12).joy.buttons[4], 0)

        controller.update_expression_action("stomp", 0.2)
        stomp = controller.step(0.21)
        self.assertEqual(stomp.joy.buttons[4], 0)
        self.assertEqual(stomp.joy.buttons[5], 1)

        # A String action may arrive one ROS tick before its cross-faded Twist.
        # It remains eligible only while the same fresh watchdog is active.
        early = SafetyController(Limits())
        early.request_stance_preparation(0.0)
        early.step(0.0)
        early.set_enabled(True, 0.1)
        early.update_expression(TwistValue(), 0.1)
        early.update_expression_action("hop", 0.1)
        self.assertEqual(early.step(0.11).joy.buttons[4], 1)

        blocked = SafetyController(Limits(), allow_dynamic_actions=False)
        blocked.request_stance_preparation(0.0)
        blocked.step(0.0)
        blocked.set_enabled(True, 0.1)
        blocked.update_expression(TwistValue(z=0.02), 0.1)
        blocked.update_expression_action("hop", 0.1)
        self.assertEqual(blocked.step(0.11).joy.buttons[4], 0)

        # A hop/stomp interrupts a locomotion command and is emitted only
        # after the bridge has returned to the torque stance.
        interrupt = SafetyController(Limits(), allow_locomotion=True, expression_timeout=1.0)
        interrupt.set_enabled(True, 0.0)
        interrupt.update_expression(TwistValue(x=0.04), 0.0)
        self.assertEqual(interrupt.step(0.01).joy.buttons[1], 1)
        self.assertEqual(interrupt.step(0.40).joy.buttons[7], 1)
        interrupt.update_expression_action("stomp", 0.41)
        ramp = interrupt.step(0.42)
        self.assertEqual(ramp.action, "gait_to_stance_zero_hold")
        self.assertEqual(ramp.joy.buttons[1], 0)
        stance = interrupt.step(0.68)
        self.assertEqual(stance.action, "gait_to_stance_minimum_hold")
        stance = interrupt.step(1.01)
        self.assertEqual(stance.joy.buttons[1], 1)
        settling = interrupt.step(1.20)
        self.assertEqual(settling.action, "gait_to_stance_settling")
        stomp = interrupt.step(1.37)
        self.assertEqual(stomp.joy.buttons[5], 1)
        self.assertEqual(stomp.joy.axes, [0.0] * 8)

    def test_generation_order_and_cancel_before_start(self):
        controller = SafetyController(Limits())
        controller.request_stance_preparation(0.0)
        controller.step(0.0)
        controller.set_enabled(True, 0.1)
        controller.update_expression(TwistValue(z=0.01), 0.1)
        controller.update_expression_action(
            "none", 0.1, kind="cancel", generation=7, occurrence="change"
        )
        controller.update_expression_action(
            "stomp", 0.1, kind="start", generation=7, occurrence="entrance:0"
        )
        cancel = controller.step(0.11)
        start = controller.step(0.12)
        self.assertEqual(cancel.joy.buttons[6], 1)
        self.assertEqual(cancel.joy.buttons[5], 0)
        self.assertEqual(start.joy.buttons[6], 0)
        self.assertEqual(start.joy.buttons[5], 1)

        # Older generations and duplicate occurrence IDs cannot replay.
        controller.update_expression_action(
            "hop", 0.13, kind="start", generation=6, occurrence="old"
        )
        controller.update_expression_action(
            "stomp", 0.14, kind="start", generation=7, occurrence="entrance:0"
        )
        self.assertEqual(controller.step(0.15).joy.buttons[4], 0)
        self.assertEqual(controller.step(0.15).joy.buttons[5], 0)

    def test_cancel_preserves_current_joy_axes(self):
        controller = SafetyController(Limits())
        controller.set_enabled(True, 0.0)
        controller.output = TwistValue(z=.01, roll=.08, pitch=-.06)
        before = controller._twist_to_joy(controller.output)
        controller.update_expression_action("none", .1, kind="cancel", generation=1)
        decision = controller.step(.1)
        self.assertEqual(decision.joy.axes, before.axes)
        self.assertEqual(decision.joy.buttons[6], 1)

    def test_tighter_limits_do_not_rescale_wire_units(self):
        controller = SafetyController(Limits(z=.01, roll=.10, pitch=.10))
        joy = controller._twist_to_joy(TwistValue(z=.007, roll=.05, pitch=-.05))
        self.assertAlmostEqual(joy.axes[2], .07)
        self.assertAlmostEqual(joy.axes[6], .08)
        self.assertAlmostEqual(joy.axes[7], -.08)

    def test_home_return_target_points_to_anchor_and_is_step_bounded(self):
        target = home_return_target(0.0, 0.0, 0.10, 0.0, 0.012)
        self.assertAlmostEqual(target[0], 0.088)
        self.assertAlmostEqual(target[1], 0.0)
        arrived = home_return_target(0.0, 0.0, 0.005, 0.0, 0.012)
        self.assertEqual(arrived, (0.0, 0.0))

    def test_recenter_transition_zeros_motion_before_restarting_gait(self):
        controller = SafetyController(
            Limits(), allow_locomotion=True, mode_transition_delay=0.35
        )
        controller.set_enabled(True, 0.0)
        controller.locomotion_ready = True
        controller.output = TwistValue(x=0.05)
        controller.output_at = 1.0

        controller.begin_recenter_transition(1.0)

        self.assertTrue(controller.output.is_zero())
        self.assertFalse(controller.locomotion_ready)
        self.assertEqual(controller.mode_stage, 1)
        self.assertAlmostEqual(controller.mode_due, 1.35)

        controller.update_expression(TwistValue(x=-0.035), 1.0)
        settling = controller.step(1.1)
        self.assertTrue(settling.twist.is_zero())
        self.assertEqual(sum(settling.joy.buttons), 0)

        restart = controller.step(1.36)
        self.assertEqual(restart.joy.buttons[7], 1)
        self.assertTrue(controller.locomotion_ready)

    def test_queued_action_outlives_expression_freshness_during_stance_transition(self):
        controller = SafetyController(
            Limits(),
            allow_locomotion=True,
            expression_timeout=0.2,
            action_queue_timeout=4.0,
            locomotion_zero_hold=0.25,
        )
        controller.set_enabled(True, 0.0)
        controller.update_expression(TwistValue(x=0.04), 0.0)
        controller.step(0.0)
        controller.update_expression(TwistValue(x=0.04), 0.35)
        controller.step(0.36)
        controller.update_expression_action("stomp", 0.37)
        controller.step(0.38)
        controller.step(0.64)
        controller.step(0.90)
        action = controller.step(1.00)
        self.assertTrue(action.stale)
        self.assertEqual(action.joy.buttons[1], 1)
        action = controller.step(1.36)
        self.assertEqual(action.joy.buttons[5], 1)

    def test_disable_emits_internal_cancel_and_exact_zero(self):
        controller = SafetyController(Limits())
        controller.set_enabled(True, 0.0)
        controller.update_expression(TwistValue(z=0.02), 0.0)
        controller.step(0.0)
        controller.set_enabled(False, 0.1)
        disabled = controller.step(0.1)
        self.assertEqual(disabled.twist, TwistValue())
        self.assertEqual(disabled.joy.buttons[6], 1)
        self.assertEqual(controller.step(0.2).joy.buttons[6], 0)

    def test_runtime_defaults_in_configuration(self):
        config_path = os.path.join(os.path.dirname(__file__), "..", "config", "default.yaml")
        with open(config_path, "r", encoding="utf-8") as stream:
            config = yaml.safe_load(stream)
        self.assertFalse(config["safety"]["motion_enabled"])
        self.assertTrue(config["safety"]["allow_locomotion"])
        self.assertTrue(config["safety"]["allow_dynamic_actions"])
        self.assertLess(
            config["safety"]["home_return"]["resume_radius"],
            config["safety"]["home_return"]["trigger_radius"],
        )
        self.assertLess(
            config["safety"]["home_return"]["trigger_radius"],
            config["safety"]["maximum_planar_displacement"],
        )
        self.assertEqual(config["chat"]["backend"], "deterministic")
        for profile in self.patterns.values():
            self.assertTrue(0.0 <= profile.intensity <= 1.0)
            self.assertGreater(profile.duration, 0.0)
            self.assertGreater(profile.speed, 0.0)
            self.assertGreater(profile.acceleration, 0.0)
            self.assertGreaterEqual(profile.cooldown, 0.0)
            self.assertGreaterEqual(profile.variation, 0.0)
            self.assertGreater(profile.transition_blend, 0.0)
            for segment in profile.transition + profile.idle:
                self.assertLessEqual(abs(segment.twist.x), config["safety"]["limits"]["linear_x"])
                self.assertLessEqual(abs(segment.twist.y), config["safety"]["limits"]["linear_y"])
                self.assertLessEqual(abs(segment.twist.yaw), config["safety"]["limits"]["angular_z"])
                self.assertIn(segment.action, EXPRESSION_ACTIONS)


class ConversationTests(unittest.TestCase):
    @staticmethod
    def wait_for(predicate, timeout=2.0):
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            if predicate():
                return
            time.sleep(0.01)
        raise AssertionError("timed out waiting for conversation event")

    def test_deterministic_stream_has_turn_ids_and_completed_text(self):
        events = []
        coordinator = ConversationCoordinator(DeterministicChatBackend(), events.append)
        turn_id = coordinator.submit("I am happy")
        self.wait_for(lambda: any(item["type"] == "completed" for item in events))
        self.assertEqual(turn_id, "turn-000001")
        for event in events:
            validate_conversation_event(event)
        self.assertTrue(any(item["type"] == "delta" for item in events))
        final = [item for item in events if item["type"] == "completed"][0]
        self.assertTrue(final["text"])
        coordinator.shutdown()

    def test_assistant_state_survives_heartbeat_overwrite(self):
        tracker = AssistantStateTracker()
        tracker.observe({"sequence": 8, "turn_id": "turn-000004", "source": "assistant"})
        tracker.observe({"sequence": 8, "turn_id": "turn-000004", "source": "heartbeat"})
        self.assertEqual(
            tracker.matching("turn-000004", 7),
            {"sequence": 8, "turn_id": "turn-000004", "source": "assistant"},
        )
        self.assertIsNone(tracker.matching("turn-000003", 7))
        tracker.reset()
        self.assertIsNone(tracker.matching("turn-000004", 7))

    def test_chat_client_wait_covers_provider_retries_and_fallback(self):
        self.assertEqual(
            chat_client_timeout(
                {"request_timeout": 20.0, "max_retries": 1, "retry_delay": 0.25}
            ),
            50.25,
        )
        self.assertEqual(
            chat_client_timeout(
                {"request_timeout": 5.0, "max_retries": 0, "retry_delay": 0.0}
            ),
            30.0,
        )

    def test_retry_failure_and_offline_fallback_are_bounded(self):
        class FailingBackend:
            name = "failing"

            def __init__(self):
                self.calls = 0

            def stream(self, *_args):
                self.calls += 1
                raise RuntimeError("secret-shaped provider error must not escape")

        failing = FailingBackend()
        events = []
        coordinator = ConversationCoordinator(
            failing,
            events.append,
            fallback_backend=DeterministicChatBackend(),
            max_retries=1,
            retry_delay=0.0,
        )
        coordinator.submit("hello")
        self.wait_for(lambda: any(item["type"] == "completed" for item in events))
        self.assertEqual(failing.calls, 2)
        self.assertEqual(len([item for item in events if item["type"] == "retrying"]), 1)
        self.assertTrue(any(item["type"] == "offline_fallback" for item in events))
        self.assertNotIn("secret-shaped", str(events))
        coordinator.shutdown()

    def test_timeout_uses_graceful_offline_fallback(self):
        class TimedOutBackend:
            name = "openai"

            def stream(self, *_args):
                raise TimeoutError("simulated request deadline")

        events = []
        coordinator = ConversationCoordinator(
            TimedOutBackend(),
            events.append,
            fallback_backend=DeterministicChatBackend(),
            max_retries=0,
        )
        coordinator.submit("hello")
        self.wait_for(lambda: any(item["type"] == "completed" for item in events))
        self.assertTrue(any(item["type"] == "offline_fallback" for item in events))
        self.assertFalse(any(item["type"] == "error" for item in events))
        self.assertNotIn("request deadline", str(events))
        coordinator.shutdown()

    def test_superseded_turn_cannot_complete_out_of_order(self):
        class SlowBackend:
            name = "slow"

            def stream(self, text, _history, _emotion, cancel):
                if text == "first":
                    cancel.wait(1.0)
                    yield "late"
                else:
                    yield "current"

        events = []
        coordinator = ConversationCoordinator(SlowBackend(), events.append, max_retries=0)
        first = coordinator.submit("first")
        second = coordinator.submit("second")
        self.wait_for(
            lambda: any(item["type"] == "completed" and item["turn_id"] == second for item in events)
        )
        self.assertTrue(any(item["type"] == "cancelled" and item["turn_id"] == first for item in events))
        self.assertFalse(any(item["type"] == "completed" and item["turn_id"] == first for item in events))
        coordinator.shutdown()

    def test_completed_turn_is_not_cancelled_by_next_turn_and_ids_are_unique(self):
        events = []
        coordinator = ConversationCoordinator(DeterministicChatBackend(), events.append)
        first = coordinator.submit("first", turn_id="stable-id")
        self.wait_for(
            lambda: any(item["type"] == "completed" and item["turn_id"] == first for item in events)
        )
        second = coordinator.submit("second")
        self.wait_for(
            lambda: any(item["type"] == "completed" and item["turn_id"] == second for item in events)
        )
        self.assertFalse(any(item["type"] == "cancelled" and item["turn_id"] == first for item in events))
        with self.assertRaises(ConversationError):
            coordinator.submit("duplicate", turn_id="stable-id")
        coordinator.shutdown()

    def test_partial_stream_failure_is_terminal_without_replaying_text(self):
        class PartialBackend:
            name = "partial"

            def stream(self, *_args):
                yield "visible once"
                raise RuntimeError("failed after first delta")

        events = []
        coordinator = ConversationCoordinator(
            PartialBackend(),
            events.append,
            fallback_backend=DeterministicChatBackend(),
            max_retries=1,
        )
        coordinator.submit("hello")
        self.wait_for(lambda: any(item["type"] == "error" for item in events))
        self.assertEqual(len([item for item in events if item["type"] == "delta"]), 1)
        self.assertFalse(any(item["type"] in ("retrying", "offline_fallback", "completed") for item in events))
        coordinator.shutdown()

    def test_turn_gate_rejects_cancelled_duplicate_and_late_assistant(self):
        def event(turn_id, index, kind, text="text"):
            result = {
                "schema_version": "1.0",
                "stamp": 1.0,
                "turn_id": turn_id,
                "turn_index": index,
                "type": kind,
            }
            if kind in ("accepted", "completed", "delta"):
                result["text"] = text
            return result

        gate = TurnGate()
        self.assertTrue(gate.accepts(event("one", 1, "accepted")))
        self.assertTrue(gate.accepts(event("two", 2, "accepted")))
        self.assertFalse(gate.accepts(event("one", 1, "completed")))
        gate.accepts(event("two", 2, "cancelled"))
        self.assertFalse(gate.accepts(event("two", 2, "completed")))
        self.assertTrue(gate.accepts(event("three", 3, "accepted")))
        self.assertTrue(gate.accepts(event("three", 3, "completed")))
        self.assertFalse(gate.accepts(event("three", 3, "completed")))


if __name__ == "__main__":
    unittest.main()
